version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bleach123
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '63790:6379'
    volumes:
      - redis-data:/data

networks:
  default:
    external:
      name: fable-network

volumes:
  postgres-data:
  redis-data: