version: '3'
services:
  fable:
    image: fable:latest
    restart: always
    container_name: fable
    ports:
      - '8000:8000'
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
networks:
  default:
    external:
      name: fable-network